### ISSUE TITLE
ДЗ#3 проверка кода

### ISSUE THREAD

**Issue by VadimZhiltsov** [denismeister/denismeister.github.io#1]
В целом хорошо.
Есть несколько ньюансов:

1. Градиент в CSS не является кросбраузерным. 
http://caniuse.com/#feat=css-gradients
Давайте сделаем так чтоб он работал в IE8+

2. В CSS указаны специфичные стили по селектору span {
Это усложнит дальнейшие использование этого тэга. Задайте эти стили через более конкретный селектор, например класс.

3. Можно использовать более семантичные теги, чем div.
nav - для навигационного меню
aside - боковое меню
header - для хедера
footer - для футера :)

**Comment by denismeister** [comment]
Исправил

**Comment by VadimZhiltsov** [comment]
Зачёт, перепроверю ещё, если у тестировщик найдёт какие-то неточности.
